# Generated by Django 2.2.6 on 2019-12-19 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=25)),
                ('meaning', models.CharField(max_length=50)),
                ('pronunciation', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Verb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='words.Word')),
            ],
        ),
        migrations.CreateModel(
            name='Phrasal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrasal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='words.Word')),
            ],
        ),
        migrations.CreateModel(
            name='Noun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='words.Word')),
            ],
        ),
        migrations.CreateModel(
            name='Expresion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expresion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='words.Word')),
            ],
        ),
        migrations.CreateModel(
            name='Adverb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adverb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='words.Word')),
            ],
        ),
        migrations.CreateModel(
            name='Adjective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='words.Word')),
            ],
        ),
    ]
