# Generated by Django 2.2.6 on 2020-03-17 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='practice',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
